@startuml
'https://plantuml.com/state-diagram

scale 350 width

stateInitialization:        Entry: Set variables and initialize pins\n Exit: Send boot message
stateOperational:           Entry: Turn led on

[*]-down->stateInitialization: Initial state
stateInitialization -down-> stateOperational: autonomous
stateOperational -up-> stateInitialization: command: reset

@enduml